### ISSUE TITLE
CMカット処理は行わず、丸ごとmp4エンコードする場合

### ISSUE THREAD

**Issue by mimaburao** [kaikoma-soft/CMcut4U-Mk2#3]
CMカットを行わず丸ごとmp4エンコードする場合に、mp4フォルダにエンコードされたファイルが行かないようです。
そのため、CMcut4U2.rbを実行するとエンコード処理が毎回入ってしまうようです。
当方の状態ですが、

- --paraedit オプションにて設定する対象ディレクトリごとのパラメータでCMカット処理を行わないを選択
- CMcut4U2.rbにてエンコードを開始する
- エンコードされる一時ディレクトリには、cmcut-01.log,ffprobe-in.log等が存在し、tmp.mp4もある。tmp.mp4はエンコードが完了している。

おそらくなのですが、エンコードが完了した証拠がCMcut4U2にて確認できないためmp4ディレクトリにエンコード済みファイルが移動しないように感じられます。（allmp4関数を経由するとmp4ディレクトリ内にエンコード対象のディレクトリが作成されていないようです）
--viewchkオプションにてエンコードされたファイルもCMカットをしたものは通常通りの動作でmpvが立ち上がります。CMカット無しのものはmpvも立ち上がりません。
以前のバージョン(0.1.0)ではCMカット無しでも問題なかったように記憶しています。

**Comment by kaikoma-soft** [comment]
work の下に tmp.mp4 があると言う事は字幕処理を有効にしていて、エンコード終了後に tmp.mp4 に字幕データを付加して、最終のmkv を出力する処理が失敗しているのだ推測します。
失敗の原因は ffmpeg のエラーメッセージを見ないと判らないので、お手数ですが -d オプションを付けてCMcut4U2 を実行した時のログを見せて頂けないでしょうか？
あと確認したい点は、
  * subtitle.ass、subtitle-2.ass　は正常に出力されているでしょうか？
  * ffmpeg は arib字幕処理が可能な ffmpeg が config.rb の中の FFMPEG_BIN で指定されているでしょうか？

以上よろしくお願いします。

**Comment by mimaburao** [comment]
対応策ありがとうございます。私の方で字幕処理有効にしておいて、airb字幕処理可能なffmpegではなかったのが原因です。https://github.com/kaikoma-soft/kaikoma-soft.github.io/blob/master/subtitle.mdを参考にしてffmpegを再コンパイルし、airblibを有効にした所mkv形式にてエンコード動画がありました。その後の処理も問題ないです。
当初CMカットの方は0.1.0と同じように処理されていたので全く考えが及ばなかったです。しかし、字幕処理をconfig.rbで指定している以上、字幕ありのtsではmkvのエンコードがないとおかしいはずでした。
一時ファイルには、subtitle.assはありましたがいつも0kbとなっていて、字幕うまく拾えなかったと思っていました。字幕有効のffmpegだとsubtitle.ass、subtitle-2.assとあり、中身もありました。

お手間をおかけしました。
まだ、ロゴ消しは試していませんがCMcut4U2が段々とブラッシュアップされていってるので楽しみです。
ありがとうござました。
参考までに私の利用しているffmpegのconfigureオプションを列記しておきます。
ffmpeg version N-98436-g806a4d5187 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --pkg-config-flags=--static --extra-libs='-lpthread -lm' --enable-openssl --enable-gpl --enable-libfreetype --enable-static --enable-cuda --enable-cuvid --enable-nvenc --enable-libnpp --enable-libaribb24 --enable-libass --enable-version3 --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-nonfree
